### ISSUE TITLE
List current provider info

### ISSUE THREAD

**Issue by fennifith** [theonesean/aight#9]
This would be extremely useful for both debugging and actual use, as I think "which provider is matched and where does it exist" might be the most complicated part of the script for users to understand.

Each provider will have its own "root directory" in which provider-specific config values (such as keywords set by #8) will be stored. Combined with all of the other strange behaviors in how the providers are matched, this could become complicated pretty quickly.

**Comment by fennifith** [comment]
After some discussion, the command for this feature will be `aight peeps`.

**Comment by theonesean** [comment]
This could also be `aight folx`
